### ISSUE TITLE
Won't Import

### ISSUE THREAD

**Issue by jafny** [CHECKROOM/checkroom_core_js#2]
Module does not event import, a oneline file with requiring the module after install yields 
![image](https://user-images.githubusercontent.com/25162983/120527269-ff3ea500-c38e-11eb-901b-21fadfb9bc17.png)

**Comment by jon-forge** [comment]
> Module does not event import, a oneline file with requiring the module after install yields ![image](https://user-images.githubusercontent.com/25162983/120527269-ff3ea500-c38e-11eb-901b-21fadfb9bc17.png)

Looks like it requires JQuery. I guess it wasn't intended to be used with Node?

**Comment by jeroenv** [comment]
CHEQROOM CoreJS is meant to be used in a browser environment and cannot be used in Node. You can find a basic example how to use CoreJS here: https://codepen.io/jeroenv/pen/ggvyYy

If you want to use the CHEQROOM API without this library you can just make the API calls directly. Here are some examples how this would work:
- [Create user](https://codepen.io/jeroenv/pen/OJgezyY)
- [Item search](https://codepen.io/jeroenv/pen/eYRWmde)
- [Create contact](https://codepen.io/jeroenv/pen/BaZpJdR)
- [Set flag](https://codepen.io/jeroenv/pen/RwVOdqL)
- [Take custody of kit](https://codepen.io/jeroenv/pen/dyvxqKB)
